// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoS0Dsa_Mlw4XarCIK6CI5dKFhiAtyemY',
    appId: '1:348491920572:web:e48715a58a6d6083810cb9',
    messagingSenderId: '348491920572',
    projectId: 'nummo-42981',
    authDomain: 'nummo-42981.firebaseapp.com',
    storageBucket: 'nummo-42981.firebasestorage.app',
    measurementId: 'G-T5D6YDGNZS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkyvDm5O1m_Xwg2Dxb5iKpSZmxHcFQLb8',
    appId: '1:348491920572:android:cf6718b1d707ac80810cb9',
    messagingSenderId: '348491920572',
    projectId: 'nummo-42981',
    storageBucket: 'nummo-42981.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCabGW4qAJXAKdZddJ09qUjG12Wf6i6A2o',
    appId: '1:348491920572:ios:c7ecde7569e15927810cb9',
    messagingSenderId: '348491920572',
    projectId: 'nummo-42981',
    storageBucket: 'nummo-42981.firebasestorage.app',
    iosClientId: '348491920572-cjsr627lsvrufe3jn5f08ckthlhcpprp.apps.googleusercontent.com',
    iosBundleId: 'com.example.nummo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCabGW4qAJXAKdZddJ09qUjG12Wf6i6A2o',
    appId: '1:348491920572:ios:c7ecde7569e15927810cb9',
    messagingSenderId: '348491920572',
    projectId: 'nummo-42981',
    storageBucket: 'nummo-42981.firebasestorage.app',
    iosClientId: '348491920572-cjsr627lsvrufe3jn5f08ckthlhcpprp.apps.googleusercontent.com',
    iosBundleId: 'com.example.nummo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoS0Dsa_Mlw4XarCIK6CI5dKFhiAtyemY',
    appId: '1:348491920572:web:465f17dcc04efdb4810cb9',
    messagingSenderId: '348491920572',
    projectId: 'nummo-42981',
    authDomain: 'nummo-42981.firebaseapp.com',
    storageBucket: 'nummo-42981.firebasestorage.app',
    measurementId: 'G-KD061Z72XM',
  );
}
