# -*- coding: utf-8 -*-
"""Algoritmo_SaludFinanciera.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t2hUyUAp_QorClvrt1vnZrLVNUqvQIos
"""

#LIBRERIAS
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

#DATASET
# Cada fila representa una persona:
#
# [ingresos, gastos, ahorro, compras_impulsivas]
#
# compras_impulsivas:
# escala de 1 a 10 siendo 1 nada y 10 máximo de compras compulsivas

datos = np.array([

    [5000, 2000, 1500, 1],
    [4500, 2500, 1200, 2],
    [4000, 3500, 300, 6],
    [3000, 2900, 100, 8],
    [2500, 2400, 50, 9],
    [6000, 2800, 2000, 1],
    [3500, 3300, 150, 7],
    [7000, 3000, 2500, 1],
    [2800, 2600, 100, 8],
    [5200, 2100, 1800, 2],
    [2000, 1950, 20, 10],
    [4800, 2600, 1000, 3],
    [3100, 3000, 50, 9],
    [5500, 2200, 1700, 1],
    [4200, 3900, 100, 7],

    [3900, 2500, 700, 4],
    [3200, 3100, 80, 8],
    [6100, 2600, 2300, 1],
    [2700, 2600, 60, 9],
    [4600, 2800, 900, 3],
    [5800, 2400, 1900, 2],
    [3300, 3200, 100, 7],
    [7200, 3500, 2600, 1],
    [2100, 2050, 30, 10],
    [4900, 2700, 1100, 3],

    [3600, 3400, 120, 7],
    [6400, 2900, 2400, 1],
    [2900, 2800, 70, 9],
    [5300, 2300, 1600, 2],
    [4100, 3800, 200, 6],
    [5700, 2500, 1800, 2],
    [3400, 3300, 90, 8],
    [6800, 3100, 2500, 1],
    [2600, 2550, 40, 10],
    [4700, 2600, 1200, 3],

    [3800, 3000, 400, 5],
    [6200, 2700, 2100, 1],
    [3000, 2950, 60, 9],
    [5400, 2400, 1700, 2],
    [4300, 4000, 100, 8],
    [5900, 2600, 2000, 1],
    [3500, 3400, 100, 7],
    [7100, 3200, 2700, 1],
    [2200, 2150, 25, 10],
    [5000, 2500, 1400, 2],

    [3700, 3100, 350, 5],
    [6500, 2800, 2400, 1],
    [2800, 2750, 50, 9],
    [5600, 2300, 1800, 2],
    [4400, 3900, 150, 7],
    [6000, 2700, 2100, 1],
    [3600, 3500, 80, 8],
    [7300, 3300, 2800, 1],
    [2300, 2250, 20, 10],
    [5100, 2600, 1500, 2]

])

# RESULTADOS ESPERADOS
# Porcentaje de salud financiera
# (0 a 100)

salud_financiera = np.array([

    95, 88, 60, 35, 20,
    98, 45, 99, 30, 92,
    10, 80, 25, 97, 50,

    72, 28, 99, 22, 78,
    94, 40, 100, 8, 82,

    42, 98, 20, 93, 55,
    95, 35, 99, 7, 84,

    65, 97, 18, 94, 30,
    98, 38, 100, 5, 90,

    68, 99, 15, 95, 45,
    97, 32, 100, 4, 91

])

#NORMALIZAR RESULTADOS: pasar de 0,** a **%
y = salud_financiera / 100

# DIVIDIR DATOS
X_train, X_test, y_train, y_test = train_test_split(
    datos,
    y,
    test_size=0.2,
    random_state=42
)

# NORMALIZAR DATOS DE ENTRADA
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# CREAR RED NEURONAL
model = Sequential()

#capa 1
model.add(Dense(
    8,
    activation='relu',
    input_shape=(4,)
))

#capa 2
model.add(Dense(
    6,
    activation='relu'
))

#salida
model.add(Dense(
    1,
    activation='sigmoid'
))

# COMPILAR MODELO
model.compile(
    optimizer='adam',
    loss='mean_squared_error',
    metrics=['mae']
)

# ENTRENAR MODELO
historial = model.fit(
    X_train,
    y_train,
    epochs=250,
    verbose=1
)

# GUARDAR MODELO
model.save("modelo_salud.keras")

#ENCONTRAR ERROR PROMEDIO
loss, mae = model.evaluate(X_test, y_test)

print("\nError promedio:", mae)

# HACER PREDICCIÓN
#
# [ingresos, gastos, ahorro, escala_deuda]
nuevo_usuario = np.array([
    [425, 7600, 650, 7]
])

nuevo_usuario = scaler.transform(nuevo_usuario)

prediccion = model.predict(nuevo_usuario)

porcentaje = prediccion[0][0] * 100

print(f"\nSalud financiera estimada: {porcentaje:.2f}%")

if porcentaje >= 80:
    print("Excelente salud financiera")

elif porcentaje >= 50:
    print("Salud financiera moderada")

else:
    print("Riesgo financiero alto")